version: '3.4'

services:        
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - eliel-network
      
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    depends_on:
      - rabbit-mq 
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    ports:
      - 9411:9411            
    networks:
      - eliel-network
      
  cambio-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: infor      
      #MYSQL_USER: root
      #MYSQL_PASSWORD: infor
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%' 
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308 
    expose: 
      - 3308 
    networks:
      - eliel-network
  
  book-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: infor      
      #MYSQL_USER: root
      #MYSQL_PASSWORD: infor
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%' 
      MYSQL_TCP_PORT: 3309
    ports:
      - 3309:3309 
    expose: 
      - 3309 
    networks:
      - eliel-network
      
  naming-server:
    image: batistondeoliveira/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - eliel-network
      
  api-gateway:
    image: batistondeoliveira/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ 
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - eliel-network
      
  cambio-service:
    image: batistondeoliveira/cambio-service    
    restart: always
    build:
      context: .
      dockerfile: 06-cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: infor
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: infor
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - eliel-network
      
  book-service:
    image: batistondeoliveira/book-service    
    restart: always
    build:
      context: .
      dockerfile: 06-book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3309/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: infor
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3309/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: infor	      
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - eliel-network
      
networks:
  eliel-network:
    driver: bridge  
